language: java

cache:
  directories:
    - $HOME/.m2

jdk:
  - openjdk8
  - openjdk9
  - openjdk11

matrix:
  allow_failures:
    - jdk: openjdk9
    - jdk: openjdk11

install: true

script: mvn clean install
